CREATE DATABASE CONTACT
USE CONTACT

--This table will store form data
CREATE TABLE EMAILDATA
(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(25),
EMAILID VARCHAR(50),
MESSAGE VARCHAR(100)
)

--This table will store user credentials
CREATE TABLE LOGIN
(
UID INT IDENTITY(1,1),
USERNAME VARCHAR(25),
[PASSWORD] VARCHAR(30)
)

--This SP will save forms data.
CREATE PROCEDURE SAVEFORMDATA (@NAME VARCHAR(25) , @EMAILID VARCHAR(50), @MESSAGE VARCHAR(100))
AS
BEGIN
INSERT INTO EMAILDATA VALUES
(
@NAME ,
@EMAILID,
@MESSAGE 
);
END


--This Sp will check if user is valid
CREATE PROCEDURE ISVALIDUSER (@USERNAME VARCHAR(25), @PASSWORD VARCHAR(30))
AS
BEGIN
SELECT COUNT(*)FROM LOGIN WHERE( USERNAME= @USERNAME AND [PASSWORD]= @PASSWORD);
END


--ADDING LOGIN CREDENTIALS
Insert into login (username, password) values ('admin','admin');



